/*
DROP DATABASE sampledb;
DROP ROLE dbadmin;
DROP ROLE hr;
DROP ROLE sh;
*/

CREATE ROLE dbadmin
    LOGIN
    CREATEDB
    CREATEROLE
    PASSWORD 'Welcome1';

CREATE ROLE hr LOGIN PASSWORD 'Welcome1';
CREATE ROLE sh LOGIN PASSWORD 'Welcome1';

GRANT hr to dbadmin;
GRANT sh to dbadmin;

\c postgres dbadmin

CREATE DATABASE sampledb
    OWNER dbadmin
    ENCODING 'UTF8'
    LC_COLLATE='en_US.UTF-8'
    LC_CTYPE='en_US.UTF-8'
    TEMPLATE template0;
	
\c sampledb dbadmin

CREATE SCHEMA AUTHORIZATION hr;
CREATE SCHEMA AUTHORIZATION sh;
GRANT CREATE ON SCHEMA hr TO hr;
GRANT CREATE ON SCHEMA sh TO sh;
GRANT USAGE ON SCHEMA hr TO hr;
GRANT USAGE ON SCHEMA sh TO sh;
